### PR TITLE
add support for python3.7

### PR DESCRIPTION
**Pull request by garanews**
- changed requirement pythonwhois with pythonwhois-alt
https://github.com/kilgoretrout1985/pythonwhois-alt
- added missing future in setup.py

### CODE REVIEW

**Comment by garanews** [comment]
can you please merge it?

**Comment by Heat-Miser** [comment]
Hello

sorry for the delay, I merge it immediately !

**Comment by certsocietegenerale** [comment]
Thank you for your contribution

**Comment by garanews** [comment]
Thanks! :)

**Comment by garanews** [comment]
Any chance to update also package on pypi?

**Pull request merged**
